{
 "title": "Jenkins Statistics",
 "time": { "from": "2025-09-25T17:41:38.693Z", "to": "2025-09-25T17:42:08.784Z" },
 "templating": {
  "list": [
   { "name": "Traces", "query": "jaeger" },
   {
    "name": "Logs",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "Metrics", "query": "prometheus" },
   { "name": "InstanceID", "query": { "query": "service.name:jenkins" } },
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  {
   "title": "JVM CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{\"jvm.system.cpu.utilization\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm.memory.used{}) / sum(jvm.memory.limit)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "service.name:jenkins AND trace_id: \"$traceId\""
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "service": "jenkins" }
   ]
  }
 ]
}