all:
  hosts:
    localhost:
  vars:
    victorialogs_version: v1.11.0
    vic_vm_alert_version: v1.111.0
    victoriametrics_version: v1.111.0
    vmauth_version: v1.111.0
    victoriametrics_service_envflag_enabled: true
    victoriametrics_service_envflag_data:
      - 'vmalert.proxyURL=http://127.0.0.1:9431'
