apiVersion: 1
datasources:
  - name: victoriametrics-prometheus
    type: prometheus
    url: 'http://victoriametrics:8428'
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.53.0
      disableRecordingRules: false
  - name: victoriametrics
    type: victoriametrics-datasource
    url: 'http://victoriametrics:8428'
    isDefault: true
    jsonData:
      httpMethod: POST
