{
 "title": "Gatus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Success rate",
   "type": "table",
   "description": "Number of successful results compared to the total number of results during the current interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[30s])) by (key) / sum(rate(gatus_results_total[30s])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gatus_results_duration_seconds", "legendFormat": "{{key}}" }
   ]
  },
  {
   "title": "Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[30s])) by (key) / sum(rate(gatus_results_total[30s])) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total results per minute",
   "type": "timeseries",
   "description": "Number of results per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total[5m])*60) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Successful results per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"true\"}[5m])*60) by (key)",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Unsuccessful results per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gatus_results_total{success=\"false\"}[5m])*60) by (key)",
     "legendFormat": "{{key}} "
    }
   ]
  }
 ]
}